### ISSUE TITLE
POST JSON input

### ISSUE THREAD

**Issue by harrytang** [yiisoft/yii-rest#15]
### What steps will reproduce the problem?
1. Add component config as in quick-start.md

>         'request' => [
>             'parsers' => [
>                 'application/json' => 'yii\web\JsonParser',
>             ]
>         ]

2. Create REST UserController as in quick-start.md

3. sending a POST request with the user data in JSON format:

> curl -X POST \
>   https://api-dev.powerkernel.com/v1/user \
>   -H 'accept: application/json' \
>   -H 'cache-control: no-cache' \
>   -H 'content-type: application/json' \
>   -H 'postman-token: 69f05323-5c9e-88bc-140c-8eac38d62fb8' \
>   -d '{"name": "My Name", "email": "xxx@gmail.com"}'

### What's expected?
HTTP/1.1 201 Created
....

### What do you get instead?
{
    "name": "Unsupported Media Type",
    "message": "",
    "code": 0,
    "status": 415,
    "type": "yii\\web\\UnsupportedMediaTypeHttpException"
}

### Additional info

| Q                | A
| ---------------- | ---
| Yii version      | 2.1-dev
| Yii REST version | @dev
| PHP version      | 7.1
| Operating system | Ubuntu 16 LTS

**Comment by samdark** [comment]
Works currently with https://github.com/yiisoft/request-body-parser
