### ISSUE TITLE
move  yii\web\NotFoundHttpException to yii\base\exceptions\NotFoundHttpException 

### ISSUE THREAD

**Issue by kids-return** [yiisoft/yii-rest#18]
move  yii\web\NotFoundHttpException to yii\base\exceptions\NotFoundHttpException 
or
dependent `yii-web`

https://github.com/yiisoft/yii-rest/blob/00d2e78857fdd785532764992cd9ee236a819040/src/Action.php#L13

**Comment by samdark** [comment]
Will eventually be done.

**Comment by samdark** [comment]
Not applicable to current package.
