### ISSUE TITLE
Bug in create action of \yii\rest\ActiveController

### ISSUE THREAD

**Issue by aminkt** [yiisoft/yii-rest#22]
### What steps will reproduce the problem?
Consider that you are using ActiveController and want to create an entity in your db.
When you send post request to create action and want check access of user that requested.

### What's expected?
You expect that the model object in checkAccess method filled by user input but it's not.

### What do you get instead?
The model object is null.

### Additional info

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.15.1
| Yii REST version | master
| PHP version     | 7.1
| Operating system | Docker ubuntu 16

Please refer to this issue:
https://github.com/yiisoft/yii2/issues/16812#issuecomment-431989302

**Comment by samdark** [comment]
I think we can even replace ID with a model, right?

**Comment by samdark** [comment]
Doesn't apply to current package.
