### ISSUE TITLE
Does this repo need depend yii-web?

### ISSUE THREAD

**Issue by kids-return** [yiisoft/yii-rest#27]
currently `yii-web` is depend `view`
`yii-rest` does not need depend `view`
I don't think this `repo` needs to depend on `yii-web`.

**Comment by samdark** [comment]
It shares a big pack of similarities since REST functions over HTTP: request/response, headers, content type negotiation etc.

**Comment by tomlutzenberger** [comment]
Splitting `yii-web` up even further would result in a huge amount of unnecessary work.
Since `yii-rest` is also web-related it makes sense as is.

**Comment by kids-return** [comment]
@tomlutzenberger 
If we don't separate 'yii-web' then we can merge `yii-rest` into `yii-web`, this repo will have no meaning.
So `yii-web` also needs to be merged into `yii-core` because `yii-web` also depends on ‘yii-core’.
This will cause us to return to the state of `yii2.0`. The time during this period is wasted.
We will always cycle between cutting and merging.

I think separation is correct. We should now concentrate all our efforts on solving problems in the process of separation.

At the moment, we only need to resolve the dependencies between `yii-web` and `yii-rest` to implement all the features of `yii2.0`.

Reference:
https://github.com/yiisoft/yii-project-template/issues/12
https://github.com/yiisoft/yii-web/pull/27

**Comment by kids-return** [comment]
> need to slice the `yii-web` public part into a repo  

or
`yii-web` depend `yii-rest` , the generic part is moved to `yii-rest`, `yii-web` for rewriting

**Comment by kids-return** [comment]
This problem also needs to be solved
See: https://github.com/yiisoft/view/issues/6

**Comment by kids-return** [comment]
@samdark @cebe @hiqsol @schmunk42 @SilverFire @klimov-paul @rob006
 What do you think?

**Comment by samdark** [comment]
Separation is fine: REST part isn't needed if you want web only but main reason for it is to make releases, issues and maintenance independent at least to some degree.

**Comment by samdark** [comment]
@kids-return how would you implement HTTP features needed for REST w/o reusing web part?

**Comment by kids-return** [comment]
1. Put the public part in a separate repo. (I don't know how to name this repo)
2. Put it in the core
3. Put it in `yii-rest`, `yii-web` depend `yii-rest` (this will ensure the minimization of `yii-rest`)

This is what I can think of now, I will find out if there are other separation schemes.

**Comment by samdark** [comment]
I think variant 3 is fine for now.

**Comment by cebe** [comment]
this depends on how much yii-web includes asset related stuff.

**Comment by samdark** [comment]
Pretty much all of it.

**Comment by kids-return** [comment]
Is there a result now?
I found that `yii-rest` is increasingly dependent on `yii-web`.
If you use scenario 3, we should move the relevant work to this repo as soon as possible.
Currently `yii-base-api` is no longer working.
This can avoid a lot of meaningless work.
I think we should focus on solving these dependencies first, so that we can avoid a lot of meaningless work.
E.g. `yii-base-api` can't work, I have to go to a lot of related repo, check commit, it's painful

**Comment by kids-return** [comment]
I can't fix before I don't know the result. ☹️

**Comment by machour** [comment]
I vote for solution 3.

**Comment by kids-return** [comment]
I vote for solution 3.

**Comment by samdark** [comment]
3, as I said before.

**Comment by kids-return** [comment]
I have started to try the related work, my steps are as follows
step 1
Move the relevant files from `yii-web` to ensure that `yii-rest` works properly.
step 2
Make `yii-web` depend on `yii-rest`. Remove unrelated files from `yii-web` and make `yii-web` difference file extend `yii-rest`
step 3 
Fix file comments related content
step 4
Move and fix tests
step 5
Move and fix docs.

Of course, problems may occur in the process.
But the promotion will be better than the stagnation.
After doing some work, I found that it might be better to separate `http` from `yii-core` to `yii-http`.
Because it is more appropriate to put `yii-rest` and `yii-web` the same content to `yii-http`.
But I want to advance according to the above steps. Other related issues will be discussed at the appropriate time

**Comment by kids-return** [comment]
`yii-rest` depends on `yii-web`?
Then `yii-rest` indirectly depends on `view`?
But in most cases `yii-rest` does not need to rely on `view`!
How to implement `api framework` like `Lumen` and `Slim`

**Comment by kids-return** [comment]
How can the current `yii-base-api` work properly?

**Comment by kids-return** [comment]
No matter which method use
I only hope that we can move forward,Instead of stagnation.
There are many other problems on the way forward.
If we don’t advance, we will never find the next problem.

**Comment by kids-return** [comment]
I want to advance according to my ideas. If you end up against it, or have a better plan, then proceed with `git reset`.

**Comment by rob006** [comment]
> I'm curious, what are your arguments against this?

Lack of sufficient arguments in favor of extracting another package. I was already against extracting `view` package because there is no real reason to do this ("you may not need some stuff" is not a valid reason for creating another package). Creating `yii-http` looks like an escalation of this over-abstracting madness, only to solve a problem which should not exist in the first place :D.

**Comment by kids-return** [comment]
So how do we now need to make yi-rest and yii-base-api work?

**Comment by kids-return** [comment]
How about letting it run first? What do you need to do next? ? ? ? ? ?

**Comment by samdark** [comment]
We've discussed it with @machour in private and decided that yii-rest should depend on yii-web.

**Comment by samdark** [comment]
Sorry for getting back and forth, @kids-return.

**Comment by jasonmccallister** [comment]
@samdark if I only wanted to build a REST API and `yii-rest` which depends on `yii-web` which includes `yii-view`, do I need views to implement a REST API?

Ideally, if I only wanted to build a REST API and use Yii as a micro-framework, I am now dependent upon `yii-views`. 

Sorry to bump this topic, but I was working on the documentation for https://github.com/yiisoft/docs/issues/32 and stumbled upon this dependency issue.

My specific use case is different as I am working on deploying Yii3 with Bref (Lambda) so extra dependencies are hot on my list. Truth be told, this is not a show stopper to include view, but as we add more dependencies my Lambda dependency/size limit gets closer to the max.

**Comment by samdark** [comment]
This repo is not ready. As for yii-web, https://github.com/yiisoft/yii-web/issues/136

**Comment by samdark** [comment]
View dependency was not necessary for yii-web. Killed.

**Comment by xepozz** [comment]
Can be closed?
