### ISSUE TITLE
How about enabling transaction in create/udpate/delete action?

### ISSUE THREAD

**Issue by razonyang** [yiisoft/yii-rest#31]
I  handling model relations by `ActiveRecord::afterSave`, but currently the create/udpate/delete action does not supports transaction, so I need to implement a wrapper to achieve that.

And I am thinking about that is there a better way make transaction as an option of Action,  so that I do not need to implement my own action? 

I got something like:

```php
class CreateAction extends \yii\rest\CreateAction {

    public $enableTransaction = true;

    public function run()  {
        if ($this->enableTransaction) {
            return $this->safeRun();
        }
        return parent::run();
    }

    public function safeRun() {
        // begin transaction
        try {
              $model = parent::run();
              // commit transaction
              return $model;
        } catch (\Throwable $e) {
              // rollback transaction
        }
    }
}
```

**Comment by TomaszKane** [comment]
Hm, IMHO transactions is a part of business logic, so enabling it here isn't a good idea?

**Comment by samdark** [comment]
As @TomaszKane said, it should be done elsewhere.
