### ISSUE TITLE
Installation via composer fail

### ISSUE THREAD

**Issue by huyanhp** [yiisoft/yii-rest#33]
### What steps will reproduce the problem?

Installation

### What's expected?

Easy installation by adding 

"yiisoft/yii2-rest": "~1.0.0"

to the require section of  composer.json.

### What do you get instead?

   - The requested package yiisoft/yii2-rest ~1.0.0 exists as yiisoft/yii2-rest[dev-master, 3.0.x-dev] but these are rejected by your constraint.

### Additional info

| Q                | A
| ---------------- | ---
| Yii version      |  2
| Yii REST version | 
| PHP version      |
| Operating system |

**Comment by samdark** [comment]
There's no need to install this package for Yii 2. It's built into the framework package. This one is for future Yii 3.0.
