### ISSUE TITLE
in ActiveDataFilter attributeMap applied before attribute validator.

### ISSUE THREAD

**Issue by vitalyspirin** [yiisoft/yii-rest#40]
If searchModel has some validator that change attribute value (like "trim" or "filter") and attributeMap is specified for that attribute then validator won't be applied since attribute is "normalized" first.

As I see in the function buildInternal() (of class \yii\data\ActiveDataFilter) normalize() is called before buildCondition():

https://github.com/yiisoft/yii2/blob/master/framework/data/ActiveDataFilter.php#L71

Value in attributeMap is on the left side of the expression in SQL WHERE clause. It would be convenient if I can change attribute value (through applying validator) before inserting it into the right side of SQL WHERE clause.

### Additional info

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.15.1?
| PHP version      | 7.1.15
| Operating system | Ubuntu 14.04.5 LTS

**Comment by samdark** [comment]
Not applicable to current package anymore.
