### ISSUE TITLE
Feature Request: Nested Resources / Routes

### ISSUE THREAD

**Issue by saada** [yiisoft/yii-rest#43]
In the Rails world they use "Resources" to describe nested routes. Here's a reference for further reading. 
http://guides.rubyonrails.org/routing.html#nested-resources

It would be great to add this feature to Yii2.

``` ruby
class Magazine < ActiveRecord::Base
  has_many :ads
end

class Ad < ActiveRecord::Base
  belongs_to :magazine
end
```

``` ruby
resources :magazines do
  resources :ads
end
```

The above code gives you these routes out of the box

```
GET      /magazines/:magazine_id/ads
GET      /magazines/:magazine_id/ads/new
POST     /magazines/:magazine_id/ads
```

**Comment by samdark** [comment]
Yes.

**Comment by samdark** [comment]
Currently it seems to be out of our scope.
